server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MS-USER
          uri: lb://MS-USER
          predicates:
            - Path=/v1/user/**
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka