spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:mysql://localhost:3308/user_db
    username: root
    password: Netec123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

springdoc:
  api-docs:
    path: /bancolombia-doc
  packages-to-scan: com.ms.user.controller
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka