spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:mysql://localhost:3308/user_db
    username: root
    password: Netec123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

springdoc:
  api-docs:
    path: /bancolombia-doc
  packages-to-scan: com.ms.user.controller